<?php
/**
 * Xcentia_Projects extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Xcentia
 * @package        Xcentia_Projects
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Project view template
 *
 * @category    Xcentia
 * @package     Xcentia_Projects
 * @author      Ultimate Module Creator
 */
?>
<?php $_project = $this->getCurrentProject();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<section class="page-header page-header-xs delivery-details">
                  <div class="container">
                  <div class="row">
                 <div class="col-lg-6 col-sm-6 col-xs-12">
                    <div class="tittle">
                              <p>Home / Describe your Idea / Customise</p>
                              <h3>Choose a Vendor</h3>
                           </div>
                  </div>
                     <!-- breadcrumbs -->

                  <div class="col-lg-6 col-sm-6 col-xs-12">
                    <div class="row process-wizard process-wizard-primary">

                        <div class="col-xs-4 process-wizard-step complete">
                           
                           <div class="progress"><div class="progress-bar"></div></div>
                           <a href="#" class="process-wizard-dot"></a>
                           <div class="text-center process-wizard-stepnum">Select Craftmen</div>
                        </div>

                        <div class="col-xs-4 process-wizard-step"><!-- complete -->
                           
                           <div class="progress"><div class="progress-bar"></div></div>
                           <a href="#" class="process-wizard-dot"></a>
                           <div class="text-center process-wizard-stepnum">Delivery Details</div>
                        </div>

                        <div class="col-xs-4 process-wizard-step"><!-- complete -->
                           
                           <div class="progress"><div class="progress-bar"></div></div>
                           <a href="#" class="process-wizard-dot"></a>
                           <div class="text-center process-wizard-stepnum">Confirmation</div>
                           
                        </div>
                     </div>
                  </div>
                  </div>
                     <!-- /breadcrumbs -->
                  </div>
               </section>
               
               
<?php $vendors = $this->getVendors($_project); ?>
<section>
	<div class="container">
	<!-- Dashborad content -->
	<div class="my-account-container">
<form action="<?php echo $this->getUrl('projects/project/vendorselected') ?>" method="post" id="product_addtocart_form" enctype="multipart/form-data">
<input type="hidden" name="project_id" value="<?php echo $_project->getId() ?>" />

	<div class="row">
		<div class="col-md-8 col-sm-8 col-xs-12"><h4>Available Craftsmen (<?php echo $vendors->getSize() ?>)</h4></div>
			<div class="col-md-4 col-sm-4 col-xs-12">
				<!--<div class="menu-sort">
					<nav>
						<ul class="list-inline menu-scrollTo categories-menu padding-bottom-10">
							<li class="pull-right"><a href="#section_3">Name<i class="fa fa-long-arrow-down"></i> </a></li>
                            <li class="pull-right"><a href="#section_4">Popularity<i class="fa fa-long-arrow-down"></i></a></li>
                           	<li class="pull-right"><a href="#">Area<i class="fa fa-long-arrow-down"></i> </a></li>
						</ul>
					</nav>--> 
                              <!-- /page menu - -> 
				</div>--> 
			</div>
	</div>
                     
	<div class="row">
		<div class="col-sm-12 col-md-12 col-xs-12">
			<?php if($vendors->getSize() > 0) { ?>
		    <table class="tbl-craftmen">
		      <thead>
		        <tr>
		          <th><label class="checkbox"><input type="checkbox" name="selectall" id="selectall" value="all"/><i></i></label></th>
		          <th>Select All</th>
		          <th>Name</th>
		          <th>Rating</th>
		          <th>Projects Completed</th>
		          <th>Address</th>
		          <th>&nbsp;</th>
		        </tr>
		      </thead>
		      <tbody>
		        <?php foreach ($vendors as $vendor): ?>
		        <tr>
		          <td data-th="Select All"><label class="checkbox"><input type="checkbox" name="vendors[]" id="vendor-<?php echo $vendor->getId() ?>" value="<?php echo $vendor->getId() ?>" /><i></i></label></td>
		          <td data-th="Name"><div class="tbl-details"><img src="<?php echo Mage::helper('xcentia_vendors/vendor_image')->init($vendor, 'logo')->keepframe(false)->resize(100); ?>" class="img-responsive"></div></td>
		          <td data-th="Name"><div class="tbl-details"><?php echo $vendor->getTitle() ?></div></td>
		          <td data-th="Rating"><div class="tbl-details"><div class="rating rating-2 size-13 margin-top-10 width-100"></div></div></td>
		          <td data-th="Projects Completed"><div class="tbl-details">500</div></td>
		          <td data-th="Address"><div class="tbl-details"><address><?php echo $vendor->getAddress1().', '.$vendor->getAddress2()?><br /><?php echo $vendor->getLandmark().', '.$vendor->getCity()?></address></div></td> 
		          <td><div class="tbl-details"><a target="_blank" href="<?php echo $this->getUrl('vendors/vendor/view', array('id'=>$vendor->getId())) ?>" class="btn btn-sm btn-info btn-bordered"><?php echo $this->__('View Profile') ?></a></div></td> 
		        </tr>
		        <?php endforeach; ?>
		      </tbody>
		    </table>
		    <div class="row padding-top-20 padding-bottom-20">
				<div class="col-md-5 col-sm-5 col-xs-12">
					<?php $product = Mage::getModel('catalog/product')->load($_project->getProductId()) ?>
					<a href="<?php echo $product->getProductUrl() ?>?redesign=<?php echo $_project->getDesignId()?>" class="btn btn-sm btn-info btn-bordered pull-left">Edit Your Design</a>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<!--<a class="btn btn-sm btn-info btn-bordered pull-left">Load More Results</a>-->
				</div>
				<div class="col-md-4 col-sm-4 col-xs-12">
					<button type="submit" class="navigate font-lato price size-20 normal-line-height"><span>Contact Selected Craftsman</span><br><i class="fa fa-long-arrow-right size-30 normal-line-height"></i></button>
				</div>
			</div>
		    <?php } else { ?>
		        <p>Sorry, no Vendors found.</p>
		    <?php } ?>
		</div>
	</div>
	</form>
</div>
</div>
</section>
<script type="text/javascript">
<!--
jQuery(document).ready(function ($) {
    $("#selectall").click(function () {
        //$(".checkbox input").attr('checked', this.checked);
		if($(this).is(':checked'))
		{
			$(".checkbox").find(':checkbox').prop('checked', true);
		}else{
			$(".checkbox").find(':checkbox').prop('checked', false);
		}
    });
});
//-->
</script>
