<?php 
$request = $this->getRequest()->getParams();
$ajaxParams = "";
if (isset($request['json']) && $request['json'] != "") {
	$ajaxParams .= "json/" . $request['json'] . "/";
}
if (isset($request['redesign']) && $request['redesign'] != "") {
	$ajaxParams .= "redesign/" . $request['redesign'] . "/";
}
if (isset($request['share']) && $request['share'] != "") {
	$ajaxParams .= "share/" . $request['share'] . "/";
}
$js_pdp = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'pdp/';
?>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!--X3 CSS-->
    <?php $jsUrl = $this->getX3JsUrl(); ?>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="<?php echo $jsUrl ?>bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo $jsUrl ?>bootstrap/css/bootstrap.vertical-tabs.css">
    <link rel="stylesheet" href="<?php echo $jsUrl ?>css/imagelistexpander.css" />
    <link rel="stylesheet" href="<?php echo $jsUrl ?>scrollbar/jquery.scrollbar.css" />
    <link rel="stylesheet" href="<?php echo $jsUrl ?>css/pdc-x3.css">
    <link href="<?php echo $js_pdp;?>jquery/colorpicker/css/colorpicker.css" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" media="only screen and (max-width: 339px)" href="<?php echo $jsUrl ?>css/mobile-320.css" />
    <link rel="stylesheet" type="text/css" media="only screen and (min-width: 340px) and (max-width: 767px)" href="<?php echo $jsUrl ?>css/mobile-480.css" />
	<link rel="stylesheet" type="text/css" media="screen and (min-width: 768px) and (max-width: 1023px)" href="<?php echo $jsUrl ?>css/tablet-768.css" />
	<link rel="stylesheet" type="text/css" media="screen and (min-width: 1024px) and (max-width: 1260px)" href="<?php echo $jsUrl ?>css/laptop-1024.css" />
    <!-- Add fancyBox main JS and CSS files -->
    <link rel="stylesheet" type="text/css" href="<?php echo $jsUrl ?>fancybox/jquery.fancybox.css" media="screen" />
    <!-- Optional theme -->
    <link rel="stylesheet" href="<?php echo $jsUrl ?>bootstrap/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="<?php echo $jsUrl ?>font-awesome-4.4.0/css/font-awesome.min.css">
    <link href="<?php echo $js_pdp;?>pdc/css/ruler.css" rel="stylesheet"/>
    <!--End X3 CSS-->


    <script src="<?php echo $js_pdp;?>jquery/jquery-1.10.2.min.js"></script>
    <script src="<?php echo $js_pdp;?>pdc/js/jquery.ruler.js"></script>
    <script src="<?php echo $js_pdp;?>jquery/colorpicker/colorpicker.js"></script>
    <script src="<?php echo $js_pdp;?>fabricjs/fabric.js"></script>
    <!--X3 JS-->
    <script src="<?php echo $js_pdp;?>pdc/js/modernizr-2.6.2.min.js"></script>
    <link href="<?php echo $jsUrl; ?>dropzone/dropzone.css" rel="stylesheet"/>
    <script src="<?php echo $jsUrl; ?>dropzone/dropzone.min.js"></script>
    <script type="text/javascript" src="<?php echo $jsUrl ?>bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo $jsUrl ?>fancybox/jquery.fancybox.js"></script>
    <script type="text/javascript" src="<?php echo $jsUrl ?>js/jquery.imagelistexpander.js"></script> 
    <script type="text/javascript" src="<?php echo $jsUrl ?>scrollbar/jquery.scrollbar.js"></script> 
    <!--<script type="text/javascript" src="<?php echo $jsUrl ?>iscroll/iscroll-zoom.js"></script>-->  
    <!--End X3 JS-->
    <link href="<?php echo $js_pdp;?>pace/dataurl.css" rel="stylesheet"/>
    <script src="<?php echo $js_pdp;?>pace/pace.min.js"></script>
	<link href="<?php echo $js_pdp; ?>pdc/css/pdc.layer.css" rel="stylesheet"/>
</head>
<body style="background-color: transparent;" class="">
<div class="iframe-container" style="display: none;">
	<button style="display: none;" id="get_design_content"><?php echo $this->__("Get Design Page") ?></button>
	<span id="close_iframe" class="close pdc-close"></span>
	<div class="pdc-wrapper" id="pdcwrapper">
		<div class="pdc-container">
			<div class="pdc-center">
				<div class="pdc_design_panel">
				<?php echo $this->__("[DON'T CHANGE THIS FILE]") ?>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	jQuery(function($) {
		var mainWindow = top.document;
		var baseUrl = $("#base_url", mainWindow).val(),
			_ifMarginTop = "10px", 
			productId = "<?php echo $request['product-id']?>";
		LoadDesign = {
			pendingTime : 0,
			baseUrl : null,
			init : function() {
				setTimeout(function() {
					LoadDesign.getDesignPage();
				}, LoadDesign.pendingTime);
			},
			getDesignPage : function() {
				var designUrl = baseUrl + "pdp/view/designtool/product-id/" + productId + "/area/customize/" + "<?php echo $ajaxParams?>";
				LoadDesign.sendRequest(designUrl, function(response) {
					if (response != "") {
						$(".pdc_design_panel").html(response);
						LoadDesign.resizeIframe();
					}
				});
			},
			sendRequest : function(url, callback) {
				$.ajax({
					type : "GET",
					url : url,
					beforeSend : function () {
						//console.log("Sending request...");
						$(".pdp_loading").show();
					},
					success : function(data) {
						callback(data);
						$(".pdp_loading").hide();
					}
				});
			},
			resizeIframe : function() {
				$("#pdc_iframe", mainWindow).css({
					"width": "100%",
					"height" : "700px",
					"left" : "0",
					"top" : "0",
					"right" : "0"
				});
                $('.main-container', mainWindow).hide();
				LoadDesign.readyToDesign();
			},
			closeIframe : function() {
				$(document).on("click", '[pdc-action="close-iframe"]', function() {
					$("#pdc_iframe", mainWindow).css({"display" : "none"}); console.log(232);
                    $('.main-container', mainWindow).show();
					$(".catalog-product-view", mainWindow).css({"overflow" : "inherit"});
				});
			}(),
			readyToDesign : function() {
				$(".loader").hide();
				$(".iframe-container").show();
				top.document.body.scrollTop = top.document.documentElement.scrollTop = 0;
			},
            //Custom theme might has different selector to main image box of product
			showSampleImage : function(mainImgBox) {
				if($("#sample_images", mainWindow).length) {
					var sampleImageStr = $("#sample_images", mainWindow).val();
					if (sampleImageStr) {
						var sampleImageJson = JSON.parse(sampleImageStr),
                            mainImgBox = mainImgBox || '#main-product-image';
						if (sampleImageJson[0] && sampleImageJson[0].image_result) {
                            //Check if result image is svg format or png
                            var thumbnail = sampleImageJson[0].image_result,
                                thumbnailFormat = thumbnail.split(".").slice(-1)[0];
                            $(mainImgBox + ' img', mainWindow).hide();
                            $("#pdc-preview", mainWindow).remove();
                            var svgPreviewObj = '<div id="pdc-preview" style="line-height: 100%;">'+ sampleImageJson[0].image_result +'</div>';
                            $(mainImgBox, mainWindow).prepend(svgPreviewObj);
                            //Disable default zoom of magento 1.9.1 - 1.9.2
                            try {
                                if(top.window.ProductMediaManager) {
                                    top.window.ProductMediaManager.destroyZoom();      
                                }
                            } catch(error) {
                                console.warn(error);
                            }
						}
						//if ($('.more-views', mainWindow).length) {
                        $('.more-views', mainWindow).remove();
                        if($(mainImgBox + ' .pdp_more_view', mainWindow).length == 0){
                            $(mainImgBox, mainWindow).append('<div class="more-views" style="clear: both; float: left;"><h2><?php echo $this->__('More Views');?></h2><ul class="pdp_more_view" style="line-height: 100%;"></ul></div>');
                        }else{
                            $('.pdp_more_view', mainWindow).html('');
                        }
                        $.each(sampleImageJson, function(index, image) {
                            if(!image.image_result) return;
                            $('.pdp_more_view', mainWindow).append('<li style="margin: 0 5px; border: 1px solid #ccc; width: 70px; float: left; cursor: pointer;"><div class="pdc-more-view-item">'+ image.image_result +'</div></li>');
                        });
                        $('.pdp_more_view li .pdc-more-view-item', mainWindow).click(function(){
                            $("#pdc-preview", mainWindow).html($(this).html()); 
                        });
						//}
					}
				}
			},
			reloadPrice : function() {
				/********************************** RELOAD PRICE **********************************/
				if ($("#product_price_config", mainWindow).length) {
					var productPriceConfig = JSON.parse($("#product_price_config", mainWindow).val());
					if (productPriceConfig.productId === undefined) {
						return false;
					}
					var extraPrice = 0;
					if ($("#extra_options_value", mainWindow).length && $("#extra_options_value", mainWindow).val() != "") {
						var extraOptionsValue = JSON.parse($("#extra_options_value", mainWindow).val()),
                            sampleCost = 0;
                        if(extraOptionsValue !== undefined) {
                            $.each(extraOptionsValue, function() {
                                sampleCost += parseFloat(this.final_price);
                            });
                        }
						if (sampleCost) {
                            extraPrice = parseFloat(sampleCost);
						}
					}
					productPriceConfig.productPrice = productPriceConfig.productPrice + extraPrice;
					productPriceConfig.productOldPrice = productPriceConfig.productOldPrice + extraPrice;
					parent.optionsPrice = new parent.Product.OptionsPrice(productPriceConfig);
					try {
                        //Reload price for configurable product
						parent.optionsPrice.reload();
                        //Reload price for simple product has custom options
                        parent.opConfig.reloadPrice();
					} catch(error) {
						console.log(error);
					}
				}
				/********************************** End RELOAD PRICE **********************************/
			},
			getDesignPageClick : function() {
				$("#get_design_content").click(function() {
					top.document.body.scrollTop = top.document.documentElement.scrollTop = 0;
					$(".catalog-product-view", mainWindow).css({"overflow" : "hidden"});
					if($(this).hasClass("loaded")) {
						//Show iframe
						$("#pdc_iframe", mainWindow).css({
							"top" : "0"
						});
                        $('.main-container', mainWindow).hide();
						return false;
					} else {
						var _initIframeW = 300;
						$("#pdc_iframe", mainWindow).css({
							"top" : ($(top.window).height() / 3) + "px",
							"left" : ($(top.window).width() - _initIframeW) / 2 + "px"
						});
					}
					$(this).addClass("loaded");
					LoadDesign.init();
				});
			}(),
			autoClickCustomBtn : function() {
				if($("#pdp_design_action", mainWindow).length && $("#pdp_design_action", mainWindow).val() != "") {
					$("#get_design_content").click();
				}
			}
 		}
 		LoadDesign.autoClickCustomBtn();
        //Auto replace base image or not
        if($("input[name='extra_options']", mainWindow).val() != "") {
            //Check config
            var pdcConfig = JSON.parse($("#pdc_product_config", mainWindow).val());
            var productConfig = JSON.parse(pdcConfig.note);
            var isAutoReplace = productConfig.auto_replace_pattern || 2;
            if($("#cart_item_id", mainWindow).val()) {
                isAutoReplace = 1;
            }
            //Edit action should replace base image
            if(isAutoReplace === 1) {
                LoadDesign.showSampleImage();
            }
        }
        LoadDesign.reloadPrice();
        document.getElementById('get_design_content').click();
	});

</script>

</body>