<?php 
$shareId = $this->getRequest()->getParam("share");
if (!$shareId) {
	return;
}
$shareInfo = $this->helper("pdp")->getShareInfo($shareId);
$thumbnail = $shareInfo['note'];
?>
<link og:image="<?php echo $thumbnail ?>" rel="image_src" href="<?php echo $thumbnail ?>"/>
<!--For facebook share. First time share should show the thumbnail-->
<meta property="og:image" content="<?php echo $thumbnail ?>"/>
<meta property="og:image:width" content="400" />
<!--End Facebook share setting-->
