<?php 
/**
 * Xcentia_Projects extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Xcentia
 * @package        Xcentia_Projects
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Project Bid list template
 *
 * @category    Xcentia
 * @package     Xcentia_Projects
 * @author      Ultimate Module Creator
 */
?>
<?php $_bids = $this->getBids(); ?>
<?php if ($_bids->getSize() > 0) :?>
<div class="bid-title">
    <h2><?php echo Mage::helper('xcentia_projects')->__('Bids') ?></h2>
</div>
<div class="bids-list-container">
    <?php foreach ($_bids as $_bid) : ?>
        <div class="bid-list-item">
            <?php echo $_bid->getAmount();?>
<br />
        </div>
    <?php endforeach;?>
</div>
<?php endif;?>
