<?php 
/**
 * Xcentia_Messages extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Xcentia
 * @package        Xcentia_Messages
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Message list template
 *
 * @category    Xcentia
 * @package     Xcentia_Messages
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_messages = $this->getMessages(); ?>
<div class="page-title message-title">
    <h1><?php echo Mage::helper('xcentia_messages')->__('Messages') ?></h1>
</div>
<?php if ($_messages->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="message-list-container">
    <?php foreach ($_messages as $_message) : ?>
        <div class="message-list-item">
            <a href="<?php echo $_message->getMessageUrl()?>">
                <?php echo $_message->getSubject();?>
            </a><br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('xcentia_messages')->__('There are no messages at this moment');?>
<?php endif;?>
