	<div class="container padding-bottom-40 padding-top-40 mainlogos">
			<!-- main container-->
            	<div class="row">
                	<div class="col-xs-12  col-sm-6 col-md-3 text-center"><a href="#"><img src="<?php echo $this->getSkinUrl(''); ?>images/collections.png" width="187" height="210" alt="Collections"></a>
                    <p>Look through
the latest unique
products here made
by our craftsmen</p></div>
                    <div class="col-xs-12  col-sm-6 col-md-3 text-center"><a href="#"><img src="<?php echo $this->getSkinUrl(''); ?>images/describe.png" width="187" height="210" alt="Describe"></a>
                    <p>Want to get something made?
Just describe it with a sketch,
text or create it using tools
provided by us.</p></div>
                    <div class="col-xs-12  col-sm-6 col-md-3 text-center"><a href="#"><img src="<?php echo $this->getSkinUrl(''); ?>images/craftsmen.png" width="187" height="210" alt="Collections"></a>
                    <p>View the list of Craftsmen and
the various things they can
customise for you.</p></div>
                    <div class="col-xs-12  col-sm-6 col-md-3 text-center"><a href="#"><img src="<?php echo $this->getSkinUrl(''); ?>images/projects.png" width="187" height="210" alt="Collections"></a>
                    <p>Look through the kind of items
people want to get custom-made.
If you think you can make it
 simply bid on the project!</p></div>
                </div>
			</div>
	 <div class="lead text-center bg-white padding-20">

                    <a href="#">How it works</a>


            </div>