<?php
$itemOption = $this->getData('item');
$buyRequest = $itemOption->getBuyRequest()->getData();
$jsonFilename = $buyRequest['extra_options'];
$images = Mage::helper('pdp')->getThumbnailImage($jsonFilename);
if($jsonFilename == "") {
	return;
}
$reviewUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK) . "pdp/view/viewdesign/json/" . $jsonFilename;
?>
<dt><span style="font-weight: bold"><?php echo $this->__('Customize Design') ?></span></dt>
<dd><a href="<?php echo $reviewUrl ?>"><?php echo $this->__('Review Your Design') ?></a></dd>



