<?php
$params = Mage::app()->getRequest()->getParams(); 
$productId = $params['productid'];
//$productColors = Mage::getModel('pdp/color')->getColors();
$productColors = Mage::getModel('pdp/pdpcolor')->getProductColorCollection($productId);
$productColors->count();
if (!$productColors->count()) {
	echo $this->__("No item found. Please add color.");
	return;
}
$productColorImageModel = Mage::getModel('pdp/pdpcolorimage');
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "pdp/images/";
$colorThumbnailUrl = $mediaUrl . "color-thumbnail/";
$_productDesignColor = Mage::helper("pdp")->getProductDesignColors($productId);
//Zend_Debug::dump($_productDesignColor);
if(!Mage::helper("pdp")->isProductColorTabEnable($productId)) {
    echo '<div style="text-align: center;">' . $this->__("NOTE: This feature required all design sides must use background image and mask/overlay image. Please edit all side and try again.") . '</div>';
    return false;
}
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('boxes.css') ?>" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->getJsUrl('pdp/backend/css/printarea.css') ?>" />
<script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/prototype.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/validation.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('scriptaculous/effects.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/form.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('pdp/jquery/jquery-1.10.2.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('pdp/backend/js/pdpdesign.js') ?>"></script>
<!--Color Picker-->
<script type="text/javascript" src="<?php echo $this->getJsUrl('pdp/backend/js/colorpicker.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('pdp/backend/js/eye.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('pdp/backend/js/layout.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('pdp/backend/js/utils.js') ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getJsUrl('pdp/backend/css/colorpicker.css') ?>"/>
<!-- Color Picker -->
<style>
    .images-container .side-images label:after { clear: both; content: "."; display: block; font-size: 0; line-height: 0;  overflow: hidden;}
</style>
<div class="pdp_message"><?php echo $this->getMessagesBlock()->toHtml(); ?></div>
<input type="hidden" id="delete_product_color_url" value="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/pdpadmin_designarea/deleteproductcolor") ?>" />
<form id="view_design_color_form" method="POST"
	action="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/pdpadmin_designarea/updatedesigncolor/"); ?>"
	enctype="multipart/form-data">
	<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
	<input type="hidden" id="current_product_id" name="product_id" value="<?php echo $productId ?>" />
	<div class='form-buttons'>
		<?php $addUrl = Mage::helper("adminhtml")->getUrl("adminhtml/pdpadmin_designarea/adddesigncolor/"); ?>
		<input type='hidden' value="<?php echo $addUrl ?>" id="add_design_color_url"/>
		<button class="scalable add add-new-design-color" type="button" title="Add Color">
			<span><span><span><?php echo $this->__('Add Color') ?></span></span></span>
		</button>
		<button class="scalable save" type="submit" title="Save">
			<span><span><span><?php echo $this->__('Save') ?></span></span></span>
		</button>
		<button class="scalable delete"
			onclick="location.reload(); return false;" title="Reset">
			<span><span><span><?php echo $this->__('Reset') ?></span></span></span>
		</button>
	</div>
	<table class="table color-image-table">
		<tr>
            <th><?php echo $this->__("Color Name") ?></th>
			<th><?php echo $this->__("Color Hexcode") ?></th>
            <!--<th>Color Thumbnail</th>-->
			<th><?php echo $this->__("Image of color") ?></th>
			<!-- <th>Thumbnail Style</th> -->
			<!-- <th>Base Image</th>  -->
			<th><?php echo $this->__("Position") ?></th>
			<!--<th>Status</th>-->
			<th><?php echo $this->__("Action") ?></th>
		</tr>
        <?php 
        //Get first side of product
        $defaultSide = $_productDesignColor['default_side'][0];
        ?>
        <tr>
            <td>
                <input type='hidden' name="default_side[side_id]" class='input-text required-entry' value='<?php echo $defaultSide['id'] ?>'/>
                <input type='text' name="default_side[color_name]" class='input-text required-entry' value='<?php echo $defaultSide['color_name'] ?>'/>
            </td>
            <td>
                <input style='background: <?php echo "#" . $defaultSide['color_code'] ?>' type='text' name="default_side[color_code]" class='input-text required-entry preview-color-code' value='<?php echo $defaultSide['color_code'] ?>'/></td>
            </td>
            <td>
                <div class='images-container'>
					<div class='side-images'>
					<?php foreach($_productDesignColor['default_side'] as $_sideDesign) : ?>
						<label style="display: block; float: none; width: 100%;"><?php echo $this->__($_sideDesign['label'])?></label>
                        <div class="color-img-item" style="position: relative;">
                            <img alt='<?php $_sideDesign['label'] ?> Image' src='<?php echo $mediaUrl . $_sideDesign['filename'] ?>' />
                            <img style="position: absolute; top: 0; left: 0;" alt='<?php $_sideDesign['label'] ?> Image' src='<?php echo $mediaUrl . $_sideDesign['overlay'] ?>' />
                        </div>
					<?php endforeach; ?>
					</div>
				</div>
            </td>
            <td><input type='text' disabled="disabled" class='input-text' value='0'/></td>
            <!--<td></td>-->
            <td></td>
        </tr>
		<?php $counter = 1; ?>
		<?php foreach ($productColors as $productColor) :?>
		<tr>
            <td><input type='text' name="color_name[<?php echo $productColor->getId() ?>]" class='input-text' value='<?php echo $productColor->getColorName() ?>'/></td>
			<td>
                <input class="preview-color-code required-entry" style='background: <?php echo "#" . $productColor->getColorCode() ?>' type='text' name="color_code[<?php echo $productColor->getId() ?>]" class='input-text' value='<?php echo $productColor->getColorCode() ?>'/>
            </td>
            <!--
            <td>
                <?php if($productColor->getColorThumbnail() !== "") : ?>
                <p>
                    <img src="<?php echo $colorThumbnailUrl . $productColor->getColorThumbnail() ?>" width="50px" style="border: 1px solid #ccc;"/>
                </p>
                <p>
                    <input type='hidden' name="color_thumbnail[<?php echo $productColor->getId() ?>]" class='input-text' value='<?php echo $productColor->getColorThumbnail() ?>'/>
                    <input type="checkbox" name="remove_thumbnail[<?php echo $productColor->getId() ?>]"/> <span><?php echo $this->__("Delete") ?></span>
                </p>
                <?php endif; ?>
                <p>
                    <input type="file" name="color_thumbnail_<?php echo $productColor->getId() ?>"/>
                </p>
                
            </td>
-->
			<td>
                
				<?php 
                //Side using image as background
                $images = $productColorImageModel->getProductColorImage($productId, $productColor->getId()); 
                ?>
				<div class='images-container'>
					<div class='side-images'>
					<?php foreach ($images as $image) : ?>
						<label style="display: block; float: none; width: 100%;"><?php echo $this->__($image->getLabel())?></label>
                        <div class="color-img-item" style="position: relative;">
                            <img alt='<?php $image->getLabel() ?> Image' src='<?php echo $mediaUrl . $image->getFilename() ?>' />
                            <img style="position: absolute; top: 0; left: 0;" alt='<?php $image->getLabel() ?> Image' src='<?php echo $mediaUrl . $image->getOverlay() ?>' />
                        </div>
					<?php endforeach; ?>
					</div>
				</div>
			</td>
			<!-- 
			<?php if ($counter == 1) :?>
			<td rowspan=<?php echo $productColors->count()?>>
				<select>
					<option value='image'><?php echo $this->__('Show Image')?></option>
					<option value='hexcode'><?php echo $this->__('Show Hexcode')?></option>
				</select>
			</td>
			 -->
			<?php endif; ?>
			<!-- <td><input type="radio" name="is_base" /></td>  -->
			<td><input type='text' name="position[<?php echo $productColor->getId() ?>]" class='input-text validate-number' value='<?php echo $productColor->getPosition() ?>'/></td>
			<!--
            <td>
				<select name="status[<?php echo $productColor->getId()?>]">
					<option <?php echo ($productColor->getStatus() == 1) ? "selected" : ""; ?> value='1'><?php echo $this->__('Enable') ?> </option>
					<option <?php echo ($productColor->getStatus() == 2) ? "selected" : ""; ?> value='2'><?php echo $this->__('Disable') ?> </option>
				</select>
			</td>
-->
			<td>
				<button id='delete_<?php echo $productColor->getId() ?>' class="delete delete-product-color"
					onclick="return false;" title="Delete">
					<span><span><span><?php echo $this->__('Delete') ?></span></span></span>
				</button>
			</td>
		</tr>
		<?php $counter++; ?>
		<?php endforeach; ?>
	</table>
</form>
<script type="text/javascript">
	var addSideColorForm = new VarienForm('view_design_color_form', true);
</script>
<div style="display: none" id="loading-mask">
    <p id="loading_mask_loader" class="loader"><img alt="Loading..." src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif')?>"><br><?php echo $this->__('Please wait...')?></p>
</div>
<script type="text/javascript">
	var addSideColorForm = new VarienForm('add_design_color_form', true);
    jQuery(function($) {
        var selector = ".preview-color-code";
        $(selector).click(function() {
            $(selector).removeClass('active');
            $(this).addClass('active');
        });
        $(selector).ColorPicker({
            //color: '#' + $(selector + '.active').val(),
            onShow: function (colpkr) {
                $(colpkr).fadeIn(300);
                return false;
            },
            onHide: function (colpkr) {
                $(colpkr).fadeOut(300);
                return false;
            },
            onChange: function (hsb, hex, rgb) {
                $(selector + '.active').css('backgroundColor', '#' + hex);
                $(".preview-color").css('backgroundColor', '#' + hex);
                $(selector + '.active').val(hex);
            }
        });
    });
</script>