<?php 
/**
 * Wa_dealer extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category   	Wa
 * @package		Wa_dealer
 * @copyright  	Copyright (c) 2013
 * @license		http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Page view template
 *
 * @category	Wa
 * @package		Wa_dealer
 * @author Ultimate Module Creator
 */
?>
<?php 
$attributes = $this->getAttributes(); 
?>
         <?php foreach($attributes as $attribute) { ?>
         <div class="form-group">
          <label><?php echo $attribute->getFrontendLabel() ?></label>
         <?php echo $this->getInputField($attribute,$this->getProduct()); ?>
          </div>
<?php } ?>