<?php 
/**
 * Xcentia_Messages extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Xcentia
 * @package        Xcentia_Messages
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Attachment list template
 *
 * @category    Xcentia
 * @package     Xcentia_Messages
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_attachments = $this->getAttachments(); ?>
<div class="page-title attachment-title">
    <h1><?php echo Mage::helper('xcentia_messages')->__('Attachments') ?></h1>
</div>
<?php if ($_attachments->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="attachment-list-container">
    <?php foreach ($_attachments as $_attachment) : ?>
        <div class="attachment-list-item">
            <a href="<?php echo $_attachment->getAttachmentUrl()?>">
                <?php echo $_attachment->getName();?>
            </a><br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('xcentia_messages')->__('There are no attachments at this moment');?>
<?php endif;?>
