<?php 
/**
 * Xcentia_Vendors extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Xcentia
 * @package        Xcentia_Vendors
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Contact list template
 *
 * @category    Xcentia
 * @package     Xcentia_Vendors
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_contacts = $this->getContacts(); ?>
<div class="page-title contact-title">
    <h1><?php echo Mage::helper('xcentia_vendors')->__('Contacts') ?></h1>
</div>
<?php if ($_contacts->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="contact-list-container">
    <?php foreach ($_contacts as $_contact) : ?>
        <div class="contact-list-item">
            <a href="<?php echo $_contact->getContactUrl()?>">
                <?php echo $_contact->getName();?>
            </a><br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('xcentia_vendors')->__('There are no contacts at this moment');?>
<?php endif;?>
