<?php
/**
 * Xcentia_Vendors extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Xcentia
 * @package        Xcentia_Vendors
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Order view template
 *
 * @category    Xcentia
 * @package     Xcentia_Vendors
 * @author      Ultimate Module Creator
 */
?>
<?php $_order = $this->getCurrentOrder();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title order-title">
    <h1><?php echo $_order->getOrderId(); ?></h1>
</div>
<div class="order-view">
    <div class="order-order_id">
        <?php echo Mage::helper('xcentia_vendors')->__('Order Id');?>:<?php echo $_order->getOrderId();?>

    </div>

</div>
