<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
	<div class="project-details">
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-sm-12">
					<!-- left text -->
					<div class="tittle">
						<p>
							<a href="<?php echo $this->getUrl() ?>">Home</a> / <a href="<?php echo $this->getUrl() ?>describe.html">Describe your idea</a> / Describe
						</p>
						<h3>Create Project</h3>
					</div>
					<!-- /left text -->
				</div>
			</div>
		</div>
	</div>
	<div class="container-fluid padding-0">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<iframe id="pdc_iframe" src=""></iframe>
			</div>
		</div>
	</div>
	
	<section class="nopadding" id="create-project-section" style="display:none;">
			<div class="project-details-head">
				<div class="container">
					<div class="row">
						<div class="col-md-12 col-sm-12">
							<!-- left text -->
							<h4 class="padding-top-20 padding-bottom-20 nomargin">Fill in the details so that the vendors can contact you based on your specifications.</h4>
						</div>
						<!-- /left text -->
					</div>
				</div>
			</div>
				<div class="container">
				<div class="row margin-left-0 margin-right-0">
				
					<!-- LEFT -->
					<div class="col-md-8 col-sm-8">
						<div class="row bg-white padding-top-20 create-project-white-area">
							<div class="col-md-12" id="main-product-image">
								<h2 class="font-lato nomargin"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2>
								<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->keepFrame(false)->resize(600) ?>" alt="image" />
							</div>
						</div>
					</div>

					<!-- RIGHT -->
					<div class="col-md-4 col-sm-4 col-xs-12">
				
							<h2 class="font-lato nomargin">Submit to Create Project</h2>
							<form action="<?php echo $this->getUrl('projects/project/create') ?>" method="post" id="create_project_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
					        <?php echo $this->getBlockHtml('formkey') ?>
					        <div class="no-display">
					            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
					            <input type="hidden" name="related_product" id="related-products-field" value="" />
					            <input type="hidden" name="type" value="design" />
					            <input type="hidden" name="save" value="0" id="save_for_future" />
					        </div>
        					<div class="form-group">
		                    	<label>Project Name</label>
		                        <input name="project_name" value="" title="Project Name" placeholder="" id="project_name" type="text" class="form-control required-entry">
		                    </div>
		                    <?php //if($_product->getSku() == 'tshirt') {
		                    if(strpos($_product->getSku(), 'tshirt') !== false) {
		                    ?>
		                    <div class="form-group">
		                    	<label class="radio-inline">
							      <input type="radio" name="size_options" value="sizeandquanity" checked>Sizes and Quantity
							    </label>
							    <label class="radio-inline">
							      <input type="radio" name="size_options" value="nameandnumbers">Name and Numbers 
							    </label>
    							<div class="size_options_wrappers row" id="sizeandquanity-wrapper">
			                    	<div class="input-group col-xs-2">
									    <span class="input-group-addon">S</span>
									    <input type="text" class="form-control" id="size-s" name="size[S]" value="0">
									</div>
									<div class="input-group col-xs-2">
									    <span class="input-group-addon">M</span>
									    <input type="text" class="form-control" id="size-s" name="size[M]" value="0">
									</div>
									<div class="input-group col-xs-2">
									    <span class="input-group-addon">L</span>
									    <input type="text" class="form-control" id="size-s" name="size[L]" value="0">
									</div>
									<div class="input-group col-xs-3">
									    <span class="input-group-addon">XL</span>
									    <input type="text" class="form-control" id="size-s" name="size[XL]" value="0">
									</div>
									<div class="input-group col-xs-3">
									    <span class="input-group-addon">XXL</span>
									    <input type="text" class="form-control" id="size-s" name="size[XXL]" value="0">
									</div>
		                      	</div>
		                      	<div class="size_options_wrappers" id="nameandnumbers-wrapper" style="display:none;">
		                      		<div class="input-group" id="namenumber-1">
									    <input type="text" placeholder="Name" class="form-control size-option-name" name="name[]" value="">
									    <input type="text" placeholder="Number" class="form-control size-option-number" name="number[]" value="">
									    <select name="size[]" class="form-control size-option-size">
									    	<option value="">-- Size --</option>
									    	<option value="L" price="0">L </option>
									    	<option value="M" price="0">M </option>
									    	<option value="S" price="0">S </option>
									    	<option value="XL" price="0">XL</option>
									    	<option value="XXL" price="0">XXL</option>
									    </select>
									    <span class="input-group-btn">
									    	<button class="btn btn-secondary removenamenumber" type="button" number="1" ><i class="fa fa-minus-square fa-2x" aria-hidden="true"></i></button>
									    </span>
									</div>
									<div id="additional-namenumbers"></div>
									 <div class="form-group">
				                    	<label>Add more <button class="btn btn-secondary" id="addnamenumber" type="button"><i class="fa fa-plus-square fa-2x" aria-hidden="true"></i></button></label>
				                    </div>
		                      	</div>
		                    </div>
		                    <?php } else { ?>
		                    <div class="form-group">
		                    	<label>Quantity</label>
		                        <input name="quantity" value="" title="Quantity" id="quantity" placeholder="How many pieces do you want?" type="text" class="form-control required-entry">
		                    </div>
		                    <?php } ?>
		                    <div class="form-group">
		                    	<label>Budget <small>(per piece)</small></label>
		                        <input name="budget" value="" title="Budget" id="budget" placeholder="Expected price per piece?" type="text" class="form-control required-entry">
		                    </div>
		                    <div class="form-group">
		                    	<label>Expected Time <small>(By when do you want it delivered?)</small></label>
		                    	<div class="row">
		                    		<div class="col-md-6"><input type="date" value="" class="form-control required-entry" name="expected[date]"></div>
		                    		<div class="col-md-6"><input type="time" value="<?php echo date("H:i", Mage::getModel('core/date')->timestamp()); ?>" class="form-control required-entry" name="expected[time]"></div>
		                    	</div>
		                    </div>
		                    <div class="form-group">
		                    	<label>Bid Close Time <small>(By when will you accepts bids?)</small></label>
		                    	<div class="row">
		                    		<div class="col-md-6"><input type="date" value="" class="form-control required-entry" name="bid_end[date]"></div>
		                    		<div class="col-md-6"><input type="time" value="<?php echo date("H:i", Mage::getModel('core/date')->timestamp()); ?>" class="form-control required-entry" name="bid_end[time]"></div>
		                    	</div>
		                    </div>
		                    {CONTAINER1}
							
							<?php echo $this->getChildHtml('design_button') ?>
							</form>
	
					</div>

				</div>
				<div class="row">
					<div class="col-md-8 col-sm-8 col-xs-12 text-left padding-20">
						<a class="btn btn-sm btn-info btn-bordered pull-left" id="design_project_<?php echo $_product->getId() ?>">Edit your design</a>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-12 text-left padding-20">
						<a href="#" class="navigate font-lato price size-20 normal-line-height pull-left" id="save_project">
                           <span>Save for future</span><br>
                           <i class="fa fa-floppy-o size-30 normal-line-height"></i>
                        </a>
                        <a href="#" class="navigate font-lato price size-20 normal-line-height pull-left" id="submit_project">
                           <span>Choose a Craftsman</span><br>
                           <i class="fa fa-long-arrow-right size-30 normal-line-height"></i>
                        </a>
					</div>
				</div>
				</div>
				
			</section>

	<script type="text/javascript">
    //<![CDATA[
        var dealerProductForm = new VarienForm('create_project_form');
        dealerProductForm = function() {
            if(this.validator.validate()) {
                this.form.submit();
            }
        }.bind(dealerProductForm);
    //]]>

    jQuery(document).ready(function($){
		$('#submit_project').click(function(){
			$('#create_project_form').submit();
		});
		$('#save_project').click(function(){
			$('#save_for_future').val('1');
			$('#create_project_form').submit();
		});

		$('input[name=size_options]').on('click', function() {
			$('.size_options_wrappers').hide();
			$('#'+$('input[name=size_options]:checked').val()+'-wrapper').show();
		});
		var namenumbercount = 1;
		$('#addnamenumber').click(function(){
			namenumbercount++;
			$('#additional-namenumbers').append('<div class="input-group" id="namenumber-'+namenumbercount+'"><input type="text" placeholder="Name" class="form-control size-option-name" name="name[]" value=""><input type="text" placeholder="Number" class="form-control size-option-number" name="number[]" value=""><select name="size[]" class="form-control size-option-size"><option value="">-- Size --</option><option value="L" price="0">L </option><option value="M" price="0">M </option><option value="S" price="0">S </option><option value="XL" price="0">XL</option><option value="XXL" price="0">XXL</option></select><span class="input-group-btn"><button class="btn btn-secondary removenamenumber" number="'+namenumbercount+'" type="button"><i class="fa fa-minus-square fa-2x" aria-hidden="true"></i></button></span></div>');
			$('.removenamenumber').unbind();
			$('.removenamenumber').click(function(){
				$('#namenumber-'+$(this).attr('number')).remove();
			});
		});
    });
	</script>
	<style>
		.design-btn {display:none}
	</style>