<?php 
/**
 * Xcentia_Messages extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Xcentia
 * @package        Xcentia_Messages
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Message Attachment list template
 *
 * @category    Xcentia
 * @package     Xcentia_Messages
 * @author      Ultimate Module Creator
 */
?>
<?php $_attachments = $this->getAttachments(); ?>
<?php if ($_attachments->getSize() > 0) :?>
<div class="attachment-title">
    <h2><?php echo Mage::helper('xcentia_messages')->__('Attachments') ?></h2>
</div>
<div class="attachments-list-container">
    <?php foreach ($_attachments as $_attachment) : ?>
        <div class="attachment-list-item">
            <a target="_blank" href="<?php echo $this->getUrl("messages/attachment/download",array("id"=>$_attachment->getId())) //echo $_attachment->getAttachmentUrl()?>">
                <?php echo $_attachment->getName();?>
            </a><br />
        </div>
    <?php endforeach;?>
</div>
<?php endif;?>
