<?php 
$fonts = $this->getFonts();
?>
<?php 
	$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'pdp/images/';
    $fontUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'pdp/fonts/';
	$baseUrl = Mage::helper("pdp")->getPdpBaseUrl();
	$fonts = Mage::getModel('pdp/pdp')->getFontCollection();
?>
<?php if(count($fonts)) : ?>
 <style>
<?php foreach ($fonts as $font) { ?>
@font-face {
    font-family: '<?php echo $font->getName(); ?>';
    src: url('<?php echo $fontUrl . $font->getName().'.'.$font->getExt(); ?>');
}
p.<?php echo str_replace(' ', '_', $font->getName()); ?> {
    font-family: <?php echo $font->getName(); ?>;
    font-size: 25px;
}
<?php }?>
<?php endif; ?>