<?php
/**
 * Xcentia_Messages extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Xcentia
 * @package        Xcentia_Messages
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Message view template
 *
 * @category    Xcentia
 * @package     Xcentia_Messages
 * @author      Ultimate Module Creator
 */
?>
<?php $_contact = $this->getCurrentContact();?>
<?php 

$customer = Mage::getSingleton('customer/session')->getCustomer();
 ?>
<div class="page-title contact-title">
    <h1><?php echo Mage::helper('xcentia_messages')->__('Add/Edit Contact ') ?></h1>
</div>
<br clear="all"/>
<div class="contact-edit">
	<form method="post" action="<?php echo $this->getUrl('vendors/contact/save'); ?>" enctype="multipart/form-data">
			<input type="hidden" name="id" value="<?php echo (is_object($_contact)) ? $_contact->getId() : '';?>" />
			<input type="hidden" name="vendor_id" value="<?php echo $customer->getId(); ?>" />
		<div class="form-group col-md-8">
			<label for="company"><?php echo Mage::helper('xcentia_vendors')->__('Name');?></label>	
			<input type="text" name="name"  title="" value="<?php echo (is_object($_contact)) ? $_contact->getName() : '';?>" class="form-control input-text" required />
		</div>
		<br clear="all" />
		<div class="form-group col-md-8">
			<label for="company"><?php echo Mage::helper('xcentia_vendors')->__('Email');?></label>	
			<input type="email" name="email"  title="" value="<?php echo (is_object($_contact)) ? $_contact->getEmail() : '';?>" class="form-control input-text" required />
		</div>
		<br clear="all" />
		<div class="form-group col-md-8">
			<label for="company"><?php echo Mage::helper('xcentia_vendors')->__('Mobile No (Include country code eg:91)');?></label>	
			<input type="text" name="mobile" pattern="^([0|\+[0-9]{1,5})?([1-9][0-9]{9})$" title="Mobile number start with country code eg:91" value="<?php echo (is_object($_contact)) ? $_contact->getMobile() : '';?>" class="form-control input-text" required />
		</div>
		<div class="form-group col-md-12" >
			<button type="submit"  class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
		</div>
	</form>
</div>
<script>
jQuery(document).ready(function($){
	
});
</script>