<?php
/**
 `* Create account form template
 * 
 * @category    design
 * @package     base_default
 * @author      Clarion Magento Team
 */
?>
<?php
/**
 * edit account form template
 *
 * @var $this Mage_Customer_Block_form_edit
 */
?>
<div class="col-md-8 col-sm-7">
	<div class="box-static box-transparent box-bordered padding-30">
		<div class="box-title margin-bottom-30">
			<h2 class="size-20"><?php echo $this->__('Edit Account Information') ?></h2>
		</div>
		<form class="nomargin sky-form" action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate">
			<?php echo $this->getBlockHtml('formkey')?>
			<fieldset>
				<div class="row">
					<div class="form-group">
						<div class="col-md-6 col-sm-6">
							<label>First Name *</label>
							<label class="input margin-bottom-10">
								<i class="ico-append fa fa-user"></i>
								<input class="required-entry" type="text" id="firstname" name="firstname" value="<?php echo $this->escapeHtml($this->getCustomer()->getFirstname()) ?>" title="First Name" maxlength="255" class="input-text required-entry">
								<b class="tooltip tooltip-bottom-right">Your First Name</b>
							</label>
						</div>
						<div class="col-md-6 col-sm-6">
							<label for="register:last_name">Last Name *</label>
							<label class="input margin-bottom-10">
								<i class="ico-append fa fa-user"></i>
								<input class="required-entry" type="text" id="lastname" name="lastname" value="<?php echo $this->escapeHtml($this->getCustomer()->getLastname()) ?>" title="Last Name" maxlength="255" class="input-text required-entry">
								<b class="tooltip tooltip-bottom-right">Your Last Name</b>
							</label>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="form-group">

						<div class="col-md-6 col-sm-6">
							<label for="email_address">Email *</label>
							<label class="input margin-bottom-10">
								<i class="ico-append fa fa-envelope"></i>
								<input class="required-entry validate-email" type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>">
								<b class="tooltip tooltip-bottom-right">Your Email</b>
							</label>
						</div>

						<div class="col-md-6 col-sm-6">
							<label for="register:phone">Phone</label>
							<label class="input margin-bottom-10">
								<i class="ico-append fa fa-phone"></i>
								<input type="tel" name="tel" id="tel" value="" class="input-text required-entry" minLength="10" maxLength="10">
								<input type="hidden" name="phone" id="phone" value="<?php echo $this->escapeHtml($this->getCustomer()->getPhone()) ?>">
								<b class="tooltip tooltip-bottom-right">Your Phone (required)</b>
							</label>
						</div>

					</div>
				</div>
			</fieldset>
			<div class="row">
				<div class="col-md-12 text-right">
					<a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a>
					<button type="button" id="submit_register" class="btn btn-primary"><i class="fa fa-check"></i> SAVE</button>
				</div>
			</div>
		</form>
	</div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function($){
    	$("#tel").intlTelInput({ preferredCountries: [ "in", "us" ],});
    	$("#tel").intlTelInput("setNumber", "<?php echo substr($this->escapeHtml($this->getCustomer()->getPhone()), -10); ?>");
    	
		$('.required-entry').addClass('required');
		jQuery.validator.addMethod('intlphone', function(value) { return (value.match(/^((\+)?[1-9]{1,2})?([-\s\.])?((\(\d{1,4}\))|\d{1,4})(([-\s\.])?[0-9]{1,12}){1,2}(\s*(ext|x)\s*\.?:?\s*([0-9]+))?$/)); }, 'Please enter a valid phone number');
		$('#form-validate').validate();
		$('#submit_register').click(function(){
			$('#phone').val( '+' + $("#tel").intlTelInput("getSelectedCountryData").dialCode + ' ' + $("#tel").val() );
			if($('#form-validate').valid()) {
				$('#form-validate').submit();
			}
		});
    });
    </script>